FROM nvcr.io/nvidia/pytorch:22.08-py3

WORKDIR /sd

RUN apt-get update

# Install font for prompt matrix
COPY /data/DejaVuSans.ttf /usr/share/fonts/truetype/

# Pip installs
RUN pip3 install albumentations
RUN pip3 install opencv-python
RUN pip3 install opencv-python-headless
RUN pip3 install pudb
RUN pip3 install imageio
RUN pip3 install imageio-ffmpeg
RUN pip3 install pytorch-lightning
RUN pip3 install omegaconf
RUN pip3 install test-tube
RUN pip3 install streamlit
RUN pip3 install einops
RUN pip3 install torch-fidelity
RUN pip3 install transformers
RUN pip3 install torchmetrics
RUN pip3 install kornia
RUN pip3 install gradio
RUN pip3 install accelerate
RUN pip3 install pynvml
RUN pip3 install basicsr
RUN pip3 install torchvision
RUN pip3 install numpy
RUN pip3 install pandas
RUN pip3 install -e git+https://github.com/hlky/facexlib#egg=facexlib
RUN pip3 install -e git+https://github.com/CompVis/taming-transformers#egg=taming-transformers
RUN pip3 install -e git+https://github.com/openai/CLIP#egg=clip
RUN pip3 install -e git+https://github.com/TencentARC/GFPGAN#egg=GFPGAN
RUN pip3 install -e git+https://github.com/xinntao/Real-ESRGAN#egg=realesrgan
RUN pip3 install -e git+https://github.com/crowsonkb/k-diffusion#egg=k_diffusion
RUN pip3 install -e git+https://github.com/francislabountyjr/stable-diffusion#egg=latent-diffusion

EXPOSE 7860

COPY ./entrypoint.sh /sd/
ENTRYPOINT /sd/entrypoint.sh